Remove getCatalog because it is horrible for performance
dapperlabs/nft-catalog pull request #135
Opened 2023-03-10 12:54 UTC by janezpodhostnik

every-time `getCatalog` is called this fetches the entire catalog from storage and copies it. This is terrible, especially since the catalog is growing.

If a specific element is needed just use the existing `getCatalogEntry` or the newly added `mustGetCatalogEntry` which just has the pre-check that was duplicated everywhere in one place.

Iteration over the entire catalog should only be used if really needed. In that case I added `forEachCatalogKey` method.

Be aware that there are examples and scripts that recommend just iterating one `catalog.keys.slice` (or equivalent). This is not a good recommendation! `catalog.keys` are not deterministically sorted! using this for paging will lead to bugs. A different mechanism should be put in place for paging.

Another performance change that I added to this is the switch from `getNFTViewsFromCap` to `getNFTViewsFromIDs` in cadence/scripts/get_nft_and_views_in_account.cdc. Because only views for a specific ID are needed, so no need getting all of them.

missing from the draft:
- I have not tested everything
- I don't know what to do with the examples that use paging
- I haven't checked any javascript code (I don't know if anything is needed)

2023-03-10 18:45 UTC, aishairzay approved these changes

2023-03-10 18:46 UTC, aishairzay requested changes
Is there a way we can not remove getCatalog and still gain these performance benefits? Many scripts and other services are using this.

2023-03-10 18:47 UTC, aishairzay commented
Please ignore the prior approval, that was an accidental click, and I can't figure out how to undo it :P

2023-03-10 18:49 UTC, aishairzay commented on cadence/contracts/NFTCatalog.cdc
> -    pub fun getCatalog() : {String : NFTCatalogMetadata} {
At best, I think we can add the new functions and put a comment above this saying not to use it.

2023-03-24 17:18 UTC, bluesign commented
You can page catalog with slice actually. Adding item to catalog is a rare event. Order is deterministic until dictionary is modified.

2023-03-27 13:25 UTC, janezpodhostnik commented
@bluesign is that how it works? Is that documented somewhere i couldn't find anything. maybe that is how it works currently and there were no guarantees given for that...

It would be great if there were some dictionary hash or something that you could pass while paging and if it changed, you would know the dictionary keys have changed.

2023-03-27 13:31 UTC, bluesign commented
@janezpodhostnik yeah it is implementation detail ( atree ) , but considering deterministic output, I don't think the order can change on cadence side per execution ( unless storage changes / dictionary modified ) 

I suggested before object hash also, but it didn't go too far. ( it would be very nice to have a hash property for resources and structs ) It would be very nice usage to check what changed in the account with storage browsing also.

2026-02-09 13:28 UTC, closed without merging